/*
 * SOC common registers and helper function/macro definitions
 *
 * Copyright (C) 2016 Piotr Dymacz <piotr@dymacz.pl>
 *
 * SPDX-License-Identifier: GPL-2.0
 */

#ifndef _QCA953X_CLOCK_H_
#define _QCA953X_CLOCK_H_

/*
 * PLL control registers
 */
#define QCA_PLL_CPU_PLL_CFG_REG	QCA_PLL_BASE_REG + 0x00
#define QCA_PLL_DDR_PLL_CFG_REG					QCA_PLL_BASE_REG + 0x04
#define QCA_PLL_CPU_DDR_CLK_CTRL_REG				QCA_PLL_BASE_REG + 0x08
#define QCA_PLL_CPU_SYNC_REG				QCA_PLL_BASE_REG + 0x0C
#define QCA_PLL_PCIE_PLL_CFG_REG			QCA_PLL_BASE_REG + 0x10
#define QCA_PLL_PCIE_PLL_DITHER_MAX_REG			QCA_PLL_BASE_REG + 0x14
#define QCA_PLL_PCIE_PLL_DITHER_MIN_REG			QCA_PLL_BASE_REG + 0x18
#define QCA_PLL_PCIE_PLL_DITHER_STEP_REG		QCA_PLL_BASE_REG + 0x1C
#define QCA_PLL_LDO_PWR_CTRL_REG			QCA_PLL_BASE_REG + 0x20
#define QCA_PLL_SWITCH_CLK_CTRL_REG			QCA_PLL_BASE_REG + 0x24
#define QCA_PLL_CURR_PCIE_PLL_DITHER_REG		QCA_PLL_BASE_REG + 0x28
#define QCA_PLL_ETH_XMII_CTRL_REG			QCA_PLL_BASE_REG + 0x2C

#define QCA_PLL_BB_PLL_CFG_REG				QCA_PLL_BASE_REG + 0x40
#define QCA_PLL_DDR_PLL_DITHER_REG			QCA_PLL_BASE_REG + 0x44
#define QCA_PLL_CPU_PLL_DITHER_REG			QCA_PLL_BASE_REG + 0x48

/*
 * PLL control registers BIT fields
 */

/* CPU_PLL_CONFIG register (CPU phase lock loop configuration) */
#define QCA_PLL_CPU_PLL_CFG_NFRAC_SHIFT	0
#define QCA_PLL_CPU_PLL_CFG_NFRAC_MASK	BITS(QCA_PLL_CPU_PLL_CFG_NFRAC_SHIFT, 6)
#define QCA_PLL_CPU_PLL_CFG_NINT_SHIFT	6
#define QCA_PLL_CPU_PLL_CFG_NINT_MASK	BITS(QCA_PLL_CPU_PLL_CFG_NINT_SHIFT, 6)
#define QCA_PLL_CPU_PLL_CFG_REFDIV_SHIFT	12
#define QCA_PLL_CPU_PLL_CFG_REFDIV_MASK		BITS(QCA_PLL_CPU_PLL_CFG_REFDIV_SHIFT, 5)
#define QCA_PLL_CPU_PLL_CFG_RANGE_SHIFT		17
#define QCA_PLL_CPU_PLL_CFG_RANGE_MASK		BITS(QCA_PLL_CPU_PLL_CFG_RANGE_SHIFT, 2)
#define QCA_PLL_CPU_PLL_CFG_OUTDIV_SHIFT	19
#define QCA_PLL_CPU_PLL_CFG_OUTDIV_MASK		BITS(QCA_PLL_CPU_PLL_CFG_OUTDIV_SHIFT, 3)

#define QCA_PLL_CPU_PLL_CFG_PLLPWD_SHIFT		30
#define QCA_PLL_CPU_PLL_CFG_PLLPWD_MASK			BIT(QCA_PLL_CPU_PLL_CFG_PLLPWD_SHIFT)
#define QCA_PLL_CPU_PLL_CFG_UPDATING_SHIFT		31
#define QCA_PLL_CPU_PLL_CFG_UPDATING_MASK		BIT(QCA_PLL_CPU_PLL_CFG_UPDATING_SHIFT)

/* ETH_XMII_CONTROL register (Ethernet XMII control) */
#define QCA_PLL_ETH_XMII_CTRL_PHASE0_CNT_SHIFT		0
#define QCA_PLL_ETH_XMII_CTRL_PHASE0_CNT_MASK		BITS(QCA_PLL_ETH_XMII_CTRL_PHASE0_CNT_SHIFT, 8)
#define QCA_PLL_ETH_XMII_CTRL_PHASE1_CNT_SHIFT		8
#define QCA_PLL_ETH_XMII_CTRL_PHASE1_CNT_MASK		BITS(QCA_PLL_ETH_XMII_CTRL_PHASE1_CNT_SHIFT, 8)
#define QCA_PLL_ETH_XMII_CTRL_OFFSET_CNT_SHIFT		16
#define QCA_PLL_ETH_XMII_CTRL_OFFSET_CNT_MASK		BITS(QCA_PLL_ETH_XMII_CTRL_OFFSET_CNT_SHIFT, 8)
#define QCA_PLL_ETH_XMII_CTRL_OFFSET_PHASE_SHIFT	24
#define QCA_PLL_ETH_XMII_CTRL_OFFSET_PHASE_MASK		BIT(QCA_PLL_ETH_XMII_CTRL_OFFSET_PHASE_SHIFT)
#define QCA_PLL_ETH_XMII_CTRL_GIGE_SHIFT		25
#define QCA_PLL_ETH_XMII_CTRL_GIGE_MASK			BIT(QCA_PLL_ETH_XMII_CTRL_GIGE_SHIFT)
#define QCA_PLL_ETH_XMII_CTRL_TX_DELAY_SHIFT		26
#define QCA_PLL_ETH_XMII_CTRL_TX_DELAY_MASK		BITS(QCA_PLL_ETH_XMII_CTRL_TX_DELAY_SHIFT, 2)
#define QCA_PLL_ETH_XMII_CTRL_RX_DELAY_SHIFT		28
#define QCA_PLL_ETH_XMII_CTRL_RX_DELAY_MASK		BITS(QCA_PLL_ETH_XMII_CTRL_RX_DELAY_SHIFT, 2)
#define QCA_PLL_ETH_XMII_CTRL_GIGE_QUAD_SHIFT		30
#define QCA_PLL_ETH_XMII_CTRL_GIGE_QUAD_MASK		BIT(QCA_PLL_ETH_XMII_CTRL_GIGE_QUAD_SHIFT)
#define QCA_PLL_ETH_XMII_CTRL_TX_INVERT_SHIFT		31
#define QCA_PLL_ETH_XMII_CTRL_TX_INVERT_MASK		BIT(QCA_PLL_ETH_XMII_CTRL_TX_INVERT_SHIFT)

/* DDR_PLL_CONFIG register (DDR PLL configuration) */
#define QCA_PLL_DDR_PLL_CFG_NFRAC_SHIFT	0
#define QCA_PLL_DDR_PLL_CFG_NFRAC_MASK	BITS(QCA_PLL_DDR_PLL_CFG_NFRAC_SHIFT, 10)
#define QCA_PLL_DDR_PLL_CFG_NINT_SHIFT	10
#define QCA_PLL_DDR_PLL_CFG_NINT_MASK	BITS(QCA_PLL_DDR_PLL_CFG_NINT_SHIFT, 6)

#define QCA_PLL_DDR_PLL_CFG_REFDIV_SHIFT	16
#define QCA_PLL_DDR_PLL_CFG_REFDIV_MASK		BITS(QCA_PLL_DDR_PLL_CFG_REFDIV_SHIFT, 5)
#define QCA_PLL_DDR_PLL_CFG_RANGE_SHIFT		21
#define QCA_PLL_DDR_PLL_CFG_RANGE_MASK		BITS(QCA_PLL_DDR_PLL_CFG_RANGE_SHIFT, 2)
#define QCA_PLL_DDR_PLL_CFG_OUTDIV_SHIFT	23
#define QCA_PLL_DDR_PLL_CFG_OUTDIV_MASK		BITS(QCA_PLL_DDR_PLL_CFG_OUTDIV_SHIFT, 3)
#define QCA_PLL_DDR_PLL_CFG_PLLPWD_SHIFT	30
#define QCA_PLL_DDR_PLL_CFG_PLLPWD_MASK		BIT(QCA_PLL_DDR_PLL_CFG_PLLPWD_SHIFT)
#define QCA_PLL_DDR_PLL_CFG_UPDATING_SHIFT	31
#define QCA_PLL_DDR_PLL_CFG_UPDATING_MASK	BIT(QCA_PLL_DDR_PLL_CFG_UPDATING_SHIFT)

/* CPU_DDR_CLOCK_CONTROL register (CPU DDR clock control) */
#define QCA_PLL_CPU_DDR_CLK_CTRL_RST_SWITCH_SHIFT			1
#define QCA_PLL_CPU_DDR_CLK_CTRL_RST_SWITCH_MASK			BIT(QCA_PLL_CPU_DDR_CLK_CTRL_RST_SWITCH_SHIFT)
#define QCA_PLL_CPU_DDR_CLK_CTRL_CPU_PLL_BYPASS_SHIFT			2
#define QCA_PLL_CPU_DDR_CLK_CTRL_CPU_PLL_BYPASS_MASK			BIT(QCA_PLL_CPU_DDR_CLK_CTRL_CPU_PLL_BYPASS_SHIFT)
#define QCA_PLL_CPU_DDR_CLK_CTRL_DDR_PLL_BYPASS_SHIFT			3
#define QCA_PLL_CPU_DDR_CLK_CTRL_DDR_PLL_BYPASS_MASK			BIT(QCA_PLL_CPU_DDR_CLK_CTRL_DDR_PLL_BYPASS_SHIFT)
#define QCA_PLL_CPU_DDR_CLK_CTRL_AHB_PLL_BYPASS_SHIFT			4
#define QCA_PLL_CPU_DDR_CLK_CTRL_AHB_PLL_BYPASS_MASK			BIT(QCA_PLL_CPU_DDR_CLK_CTRL_AHB_PLL_BYPASS_SHIFT)
#define QCA_PLL_CPU_DDR_CLK_CTRL_CPU_POST_DIV_SHIFT			5
#define QCA_PLL_CPU_DDR_CLK_CTRL_CPU_POST_DIV_MASK			BITS(QCA_PLL_CPU_DDR_CLK_CTRL_CPU_POST_DIV_SHIFT, 5)
#define QCA_PLL_CPU_DDR_CLK_CTRL_DDR_POST_DIV_SHIFT			10
#define QCA_PLL_CPU_DDR_CLK_CTRL_DDR_POST_DIV_MASK			BITS(QCA_PLL_CPU_DDR_CLK_CTRL_DDR_POST_DIV_SHIFT, 5)
#define QCA_PLL_CPU_DDR_CLK_CTRL_AHB_POST_DIV_SHIFT			15
#define QCA_PLL_CPU_DDR_CLK_CTRL_AHB_POST_DIV_MASK			BITS(QCA_PLL_CPU_DDR_CLK_CTRL_AHB_POST_DIV_SHIFT, 5)

#define QCA_PLL_CPU_DDR_CLK_CTRL_CPUCLK_FROM_CPUPLL_SHIFT	20
#define QCA_PLL_CPU_DDR_CLK_CTRL_CPUCLK_FROM_CPUPLL_MASK	BIT(QCA_PLL_CPU_DDR_CLK_CTRL_CPUCLK_FROM_CPUPLL_SHIFT)
#define QCA_PLL_CPU_DDR_CLK_CTRL_DDRCLK_FROM_DDRPLL_SHIFT	21
#define QCA_PLL_CPU_DDR_CLK_CTRL_DDRCLK_FROM_DDRPLL_MASK	BIT(QCA_PLL_CPU_DDR_CLK_CTRL_DDRCLK_FROM_DDRPLL_SHIFT)

#define QCA_PLL_CPU_DDR_CLK_CTRL_CPU_RST_EN_BP_ASRT_SHIFT		22
#define QCA_PLL_CPU_DDR_CLK_CTRL_CPU_RST_EN_BP_ASRT_MASK		BIT(QCA_PLL_CPU_DDR_CLK_CTRL_CPU_RST_EN_BP_ASRT_SHIFT)
#define QCA_PLL_CPU_DDR_CLK_CTRL_CPU_RST_EN_BP_DEASRT_SHIFT		23
#define QCA_PLL_CPU_DDR_CLK_CTRL_CPU_RST_EN_BP_DEASRT_MASK		BIT(QCA_PLL_CPU_DDR_CLK_CTRL_CPU_RST_EN_BP_DEASRT_SHIFT)
#define QCA_PLL_CPU_DDR_CLK_CTRL_AHBCLK_FROM_DDRPLL_SHIFT		24
#define QCA_PLL_CPU_DDR_CLK_CTRL_AHBCLK_FROM_DDRPLL_MASK		BIT(QCA_PLL_CPU_DDR_CLK_CTRL_AHBCLK_FROM_DDRPLL_SHIFT)

/* PCIE_PLL_CONFIG register (PCIE RC phase lock loop configuration) */
#define QCA_PLL_PCIE_PLL_CFG_REFDIV_SHIFT	10
#define QCA_PLL_PCIE_PLL_CFG_REFDIV_MASK	BITS(QCA_PLL_PCIE_PLL_CFG_REFDIV_SHIFT, 5)
#define QCA_PLL_PCIE_PLL_CFG_BYPASS_SHIFT	16
#define QCA_PLL_PCIE_PLL_CFG_BYPASS_MASK	BIT(QCA_PLL_PCIE_PLL_CFG_BYPASS_SHIFT)
#define QCA_PLL_PCIE_PLL_CFG_PLLPWD_SHIFT	30
#define QCA_PLL_PCIE_PLL_CFG_PLLPWD_MASK	BIT(QCA_PLL_PCIE_PLL_CFG_PLLPWD_SHIFT)
#define QCA_PLL_PCIE_PLL_CFG_UPDATING_SHIFT	31
#define QCA_PLL_PCIE_PLL_CFG_UPDATING_MASK	BIT(QCA_PLL_PCIE_PLL_CFG_UPDATING_SHIFT)

/* PCIE_PLL_DITHER_DIV_MAX (PCIE PLL dither parameter) */
#define QCA_PLL_PCIE_PLL_DITHER_MAX_NFRAC_MAX_SHIFT	1
#define QCA_PLL_PCIE_PLL_DITHER_MAX_NFRAC_MAX_MASK	BITS(QCA_PLL_PCIE_PLL_DITHER_MAX_NFRAC_MAX_SHIFT, 14)
#define QCA_PLL_PCIE_PLL_DITHER_MAX_NINT_MAX_SHIFT	15
#define QCA_PLL_PCIE_PLL_DITHER_MAX_NINT_MAX_MASK	BITS(QCA_PLL_PCIE_PLL_DITHER_MAX_NINT_MAX_SHIFT, 6)
#define QCA_PLL_PCIE_PLL_DITHER_MAX_USE_MAX_SHIFT	30
#define QCA_PLL_PCIE_PLL_DITHER_MAX_USE_MAX_MASK	BIT(QCA_PLL_PCIE_PLL_DITHER_MAX_USE_MAX_SHIFT)
#define QCA_PLL_PCIE_PLL_DITHER_MAX_DITHER_EN_SHIFT	31
#define QCA_PLL_PCIE_PLL_DITHER_MAX_DITHER_EN_MASK	BIT(QCA_PLL_PCIE_PLL_DITHER_MAX_DITHER_EN_SHIFT)

/* PCIE_PLL_DITHER_DIV_MIN (PCIE PLL dither parameter) */
#define QCA_PLL_PCIE_PLL_DITHER_MIN_NFRAC_MIN_SHIFT	1
#define QCA_PLL_PCIE_PLL_DITHER_MIN_NFRAC_MIN_MASK	BITS(QCA_PLL_PCIE_PLL_DITHER_MIN_NFRAC_MIN_SHIFT, 14)
#define QCA_PLL_PCIE_PLL_DITHER_MIN_NINT_MIN_SHIFT	15
#define QCA_PLL_PCIE_PLL_DITHER_MIN_NINT_MIN_MASK	BITS(QCA_PLL_PCIE_PLL_DITHER_MIN_NINT_MIN_SHIFT, 6)

/* PCIE_PLL_DITHER_STEP (PCIE PLL dither parameter) */
#define QCA_PLL_PCIE_PLL_DITHER_STEP_NFRAC_STEP_SHIFT	1
#define QCA_PLL_PCIE_PLL_DITHER_STEP_NFRAC_STEP_MASK	BITS(QCA_PLL_PCIE_PLL_DITHER_STEP_NFRAC_STEP_SHIFT, 14)
#define QCA_PLL_PCIE_PLL_DITHER_STEP_NINT_STEP_SHIFT	15
#define QCA_PLL_PCIE_PLL_DITHER_STEP_NINT_STEP_MASK	BITS(QCA_PLL_PCIE_PLL_DITHER_STEP_NINT_STEP_SHIFT, 10)
#define QCA_PLL_PCIE_PLL_DITHER_STEP_UPDATE_CNT_SHIFT	28
#define QCA_PLL_PCIE_PLL_DITHER_STEP_UPDATE_CNT_MASK	BITS(QCA_PLL_PCIE_PLL_DITHER_STEP_UPDATE_CNT_SHIFT, 4)

/* SWITCH_CLOCK_CONTROL */
#define QCA_PLL_SWITCH_CLK_CTRL_SWITCH_CLK_SEL_SHIFT			0
#define QCA_PLL_SWITCH_CLK_CTRL_SWITCH_CLK_SEL_MASK			BIT(QCA_PLL_SWITCH_CLK_CTRL_SWITCH_CLK_SEL_SHIFT)
#define QCA_PLL_SWITCH_CLK_CTRL_SWITCH_TEST_MODE_SHIFT			1
#define QCA_PLL_SWITCH_CLK_CTRL_SWITCH_TEST_MODE_MASK			BIT(QCA_PLL_SWITCH_CLK_CTRL_SWITCH_TEST_MODE_SHIFT)
#define QCA_PLL_SWITCH_CLK_CTRL_SWITCH_CLK_OFF_SHIFT			2
#define QCA_PLL_SWITCH_CLK_CTRL_SWITCH_CLK_OFF_MASK			BIT(QCA_PLL_SWITCH_CLK_CTRL_SWITCH_CLK_OFF_SHIFT)
#define QCA_PLL_SWITCH_CLK_CTRL_EEE_EN_SHIFT				3
#define QCA_PLL_SWITCH_CLK_CTRL_EEE_EN_MASK				BIT(QCA_PLL_SWITCH_CLK_CTRL_EEE_EN_SHIFT)
#define QCA_PLL_SWITCH_CLK_CTRL_ETH_PHY_PLL_EN_SHIFT			4
#define QCA_PLL_SWITCH_CLK_CTRL_ETH_PHY_PLL_EN_MASK			BIT(QCA_PLL_SWITCH_CLK_CTRL_ETH_PHY_PLL_EN_SHIFT)
#define QCA_PLL_SWITCH_CLK_CTRL_ETH_PHY_125MHZ_DIS_SHIFT		5
#define QCA_PLL_SWITCH_CLK_CTRL_ETH_PHY_125MHZ_DIS_MASK			BIT(QCA_PLL_SWITCH_CLK_CTRL_ETH_PHY_125MHZ_DIS_SHIFT)
#define QCA_PLL_SWITCH_CLK_CTRL_MDIO_CLK_SEL_SHIFT			6
#define QCA_PLL_SWITCH_CLK_CTRL_MDIO_CLK_SEL_MASK			BIT(QCA_PLL_SWITCH_CLK_CTRL_MDIO_CLK_SEL_SHIFT)

#define QCA_PLL_SWITCH_CLK_CTRL_HSUART_CLK_SEL_SHIFT				7
#define QCA_PLL_SWITCH_CLK_CTRL_HSUART_CLK_SEL_MASK				BIT(QCA_PLL_SWITCH_CLK_CTRL_HSUART_CLK_SEL_SHIFT)
#define QCA_PLL_SWITCH_CLK_CTRL_USB_CLK_SEL_SHIFT				8
#define QCA_PLL_SWITCH_CLK_CTRL_USB_CLK_SEL_MASK				BITS(QCA_PLL_SWITCH_CLK_CTRL_USB_CLK_SEL_SHIFT, 4)
#define QCA_PLL_SWITCH_CLK_CTRL_USB_CLK_SEL_25M_VAL				0x2
#define QCA_PLL_SWITCH_CLK_CTRL_USB_CLK_SEL_40M_VAL				0x5

/* DDR_PLL_DITHER register (DDR PLL dither parameter) */
#define QCA_PLL_DDR_PLL_DITHER_NFRAC_MAX_SHIFT		0
#define QCA_PLL_DDR_PLL_DITHER_NFRAC_MAX_MASK		BITS(QCA_PLL_DDR_PLL_DITHER_NFRAC_MAX_SHIFT, 10)
#define QCA_PLL_DDR_PLL_DITHER_NFRAC_MIN_SHIFT		10
#define QCA_PLL_DDR_PLL_DITHER_NFRAC_MIN_MASK		BITS(QCA_PLL_DDR_PLL_DITHER_NFRAC_MIN_SHIFT, 10)

#define QCA_PLL_DDR_PLL_DITHER_NFRAC_STEP_SHIFT			20
#define QCA_PLL_DDR_PLL_DITHER_NFRAC_STEP_MASK			BITS(QCA_PLL_DDR_PLL_DITHER_NFRAC_MIN_SHIFT, 7)
#define QCA_PLL_DDR_PLL_DITHER_UPDATE_CNT_SHIFT			27
#define QCA_PLL_DDR_PLL_DITHER_UPDATE_CNT_MASK			BITS(QCA_PLL_DDR_PLL_DITHER_UPDATE_CNT_SHIFT, 4)
#define QCA_PLL_DDR_PLL_DITHER_DITHER_EN_SHIFT			31
#define QCA_PLL_DDR_PLL_DITHER_DITHER_EN_MASK			BIT(QCA_PLL_DDR_PLL_DITHER_DITHER_EN_SHIFT)

/* CPU_PLL_DITHER register (CPU PLL dither parameter) */
#define QCA_PLL_CPU_PLL_DITHER_NFRAC_MAX_SHIFT		0
#define QCA_PLL_CPU_PLL_DITHER_NFRAC_MAX_MASK		BITS(QCA_PLL_CPU_PLL_DITHER_NFRAC_MAX_SHIFT, 6)
#define QCA_PLL_CPU_PLL_DITHER_NFRAC_MIN_SHIFT		6
#define QCA_PLL_CPU_PLL_DITHER_NFRAC_MIN_MASK		BITS(QCA_PLL_CPU_PLL_DITHER_NFRAC_MIN_SHIFT, 6)
#define QCA_PLL_CPU_PLL_DITHER_NFRAC_STEP_SHIFT		12
#define QCA_PLL_CPU_PLL_DITHER_NFRAC_STEP_MASK		BITS(QCA_PLL_CPU_PLL_DITHER_NFRAC_MIN_SHIFT, 6)
#define QCA_PLL_CPU_PLL_DITHER_UPDATE_CNT_SHIFT		18
#define QCA_PLL_CPU_PLL_DITHER_UPDATE_CNT_MASK		BITS(QCA_PLL_CPU_PLL_DITHER_UPDATE_CNT_SHIFT, 6)

#define QCA_PLL_CPU_PLL_DITHER_DITHER_EN_SHIFT				31
#define QCA_PLL_CPU_PLL_DITHER_DITHER_EN_MASK				BIT(QCA_PLL_CPU_PLL_DITHER_DITHER_EN_SHIFT)
/*
 * PLL SRIF registers (not available in AR933x)
 */
#define QCA_PLL_SRIF_BB_DPLL_BASE_REG		QCA_PLL_SRIF_BASE_REG + 0x180
#define QCA_PLL_SRIF_AUD_DPLL_BASE_REG		QCA_PLL_SRIF_BASE_REG + 0x200

#define QCA_PLL_SRIF_CPU_DPLL_BASE_REG	QCA_PLL_SRIF_BASE_REG + 0x1C0
#define QCA_PLL_SRIF_DDR_DPLL_BASE_REG	QCA_PLL_SRIF_BASE_REG + 0x240
#define QCA_PLL_SRIF_PCIE_DPLL_BASE_REG	QCA_PLL_SRIF_BASE_REG + 0xC00

#define QCA_PLL_SRIF_BB_DPLL1_REG		QCA_PLL_SRIF_BB_DPLL_BASE_REG + 0x0
#define QCA_PLL_SRIF_BB_DPLL2_REG		QCA_PLL_SRIF_BB_DPLL_BASE_REG + 0x4
#define QCA_PLL_SRIF_BB_DPLL3_REG		QCA_PLL_SRIF_BB_DPLL_BASE_REG + 0x8
#define QCA_PLL_SRIF_BB_DPLL4_REG		QCA_PLL_SRIF_BB_DPLL_BASE_REG + 0xC

#define QCA_PLL_SRIF_CPU_DPLL1_REG		QCA_PLL_SRIF_CPU_DPLL_BASE_REG + 0x0
#define QCA_PLL_SRIF_CPU_DPLL2_REG		QCA_PLL_SRIF_CPU_DPLL_BASE_REG + 0x4
#define QCA_PLL_SRIF_CPU_DPLL3_REG		QCA_PLL_SRIF_CPU_DPLL_BASE_REG + 0x8
#define QCA_PLL_SRIF_CPU_DPLL4_REG		QCA_PLL_SRIF_CPU_DPLL_BASE_REG + 0xC

#define QCA_PLL_SRIF_AUD_DPLL1_REG		QCA_PLL_SRIF_AUD_DPLL_BASE_REG + 0x0
#define QCA_PLL_SRIF_AUD_DPLL2_REG		QCA_PLL_SRIF_AUD_DPLL_BASE_REG + 0x4
#define QCA_PLL_SRIF_AUD_DPLL3_REG		QCA_PLL_SRIF_AUD_DPLL_BASE_REG + 0x8
#define QCA_PLL_SRIF_AUD_DPLL4_REG		QCA_PLL_SRIF_AUD_DPLL_BASE_REG + 0xC

#define QCA_PLL_SRIF_DDR_DPLL1_REG		QCA_PLL_SRIF_DDR_DPLL_BASE_REG + 0x0
#define QCA_PLL_SRIF_DDR_DPLL2_REG		QCA_PLL_SRIF_DDR_DPLL_BASE_REG + 0x4
#define QCA_PLL_SRIF_DDR_DPLL3_REG		QCA_PLL_SRIF_DDR_DPLL_BASE_REG + 0x8
#define QCA_PLL_SRIF_DDR_DPLL4_REG		QCA_PLL_SRIF_DDR_DPLL_BASE_REG + 0xC

#define QCA_PLL_SRIF_PCIE_DPLL1_REG		QCA_PLL_SRIF_PCIE_DPLL_BASE_REG + 0x0
#define QCA_PLL_SRIF_PCIE_DPLL2_REG		QCA_PLL_SRIF_PCIE_DPLL_BASE_REG + 0x4
#define QCA_PLL_SRIF_PCIE_DPLL3_REG		QCA_PLL_SRIF_PCIE_DPLL_BASE_REG + 0x8
#define QCA_PLL_SRIF_PCIE_DPLL4_REG		QCA_PLL_SRIF_PCIE_DPLL_BASE_REG + 0xC

/*
 * PLL SRIF registers BIT fields (not available in AR933x)
 */

/* DPLL1 (common for BB, CPU, AUD, DDR and PCIE) */
#define QCA_PLL_SRIF_DPLL1_NFRAC_SHIFT	0
#define QCA_PLL_SRIF_DPLL1_NFRAC_MASK	BITS(QCA_PLL_SRIF_DPLL1_NFRAC_SHIFT, 18)
#define QCA_PLL_SRIF_DPLL1_NINT_SHIFT	18
#define QCA_PLL_SRIF_DPLL1_NINT_MASK	BITS(QCA_PLL_SRIF_DPLL1_NINT_SHIFT, 9)
#define QCA_PLL_SRIF_DPLL1_REFDIV_SHIFT	27
#define QCA_PLL_SRIF_DPLL1_REFDIV_MASK	BITS(QCA_PLL_SRIF_DPLL1_REFDIV_SHIFT, 5)

/* DPLL2 (common for BB, CPU, AUD, DDR and PCIE) */
#define QCA_PLL_SRIF_DPLL2_RST_TEST_SHIFT	0
#define QCA_PLL_SRIF_DPLL2_RST_TEST_MASK	BIT(QCA_PLL_SRIF_DPLL2_RST_TEST_SHIFT)
#define QCA_PLL_SRIF_DPLL2_SEL_CNT_SHIFT	1
#define QCA_PLL_SRIF_DPLL2_SEL_CNT_MASK		BIT(QCA_PLL_SRIF_DPLL2_SEL_CNT_SHIFT)
#define QCA_PLL_SRIF_DPLL2_TEST_IN_SHIFT	2
#define QCA_PLL_SRIF_DPLL2_TEST_IN_MASK		BITS(QCA_PLL_SRIF_DPLL2_TEST_IN_SHIFT, 10)
#define QCA_PLL_SRIF_DPLL2_PHASE_SHIFT_SHIFT	12
#define QCA_PLL_SRIF_DPLL2_PHASE_SHIFT_MASK	BITS(QCA_PLL_SRIF_DPLL2_PHASE_SHIFT_SHIFT, 7)
#define QCA_PLL_SRIF_DPLL2_OUTDIV_SHIFT		19
#define QCA_PLL_SRIF_DPLL2_OUTDIV_MASK		BITS(QCA_PLL_SRIF_DPLL2_OUTDIV_SHIFT, 3)
#define QCA_PLL_SRIF_DPLL2_PLLPWD_SHIFT		22
#define QCA_PLL_SRIF_DPLL2_PLLPWD_MASK		BIT(QCA_PLL_SRIF_DPLL2_PLLPWD_SHIFT)
#define QCA_PLL_SRIF_DPLL2_SEL_1SDM_SHIFT	23
#define QCA_PLL_SRIF_DPLL2_SEL_1SDM_MASK	BIT(QCA_PLL_SRIF_DPLL2_SEL_1SDM_SHIFT)
#define QCA_PLL_SRIF_DPLL2_NEGTRIG_EN_SHIFT	24
#define QCA_PLL_SRIF_DPLL2_NEGTRIG_EN_MASK	BIT(QCA_PLL_SRIF_DPLL2_NEGTRIG_EN_SHIFT)
#define QCA_PLL_SRIF_DPLL2_KD_SHIFT		25
#define QCA_PLL_SRIF_DPLL2_KD_MASK		BITS(QCA_PLL_SRIF_DPLL2_KD_SHIFT, 4)
#define QCA_PLL_SRIF_DPLL2_KI_SHIFT		29
#define QCA_PLL_SRIF_DPLL2_KI_MASK		BITS(QCA_PLL_SRIF_DPLL2_KD_SHIFT, 2)
#define QCA_PLL_SRIF_DPLL2_LOCAL_PLL_SHIFT	31
#define QCA_PLL_SRIF_DPLL2_LOCAL_PLL_MASK	BIT(QCA_PLL_SRIF_DPLL2_LOCAL_PLL_SHIFT)

/* DPLL3 (common for BB, CPU, AUD, DDR and PCIE) */
/* DPLL4 (common for BB, CPU, AUD, DDR and PCIE) */

/*
 * TODO: check and confirm DPLL3/4 register structure
 */


rt_uint32_t qca953x_get_xtal_hz(void);
void qca953x_clock_init(void);

/*
 * Useful clock variables
 */
#define VAL_40MHz	(40 * 1000 * 1000)
#define VAL_25MHz	(25 * 1000 * 1000)

#endif /* _SOC_COMMON_H_ */
