/*
 * SOC common registers and helper function/macro definitions
 *
 * Copyright (C) 2016 Piotr Dymacz <piotr@dymacz.pl>
 *
 * SPDX-License-Identifier: GPL-2.0
 */

#ifndef _AR933X_GPIO_H_
#define _AR933X_GPIO_H_

/*
 * GPIO registers BIT fields
 */
#define GPIO_X_MASK(_gpio)	(1 << _gpio)

#define GPIO0	GPIO_X_MASK(0)
#define GPIO1	GPIO_X_MASK(1)
#define GPIO2	GPIO_X_MASK(2)
#define GPIO3	GPIO_X_MASK(3)
#define GPIO4	GPIO_X_MASK(4)
#define GPIO5	GPIO_X_MASK(5)
#define GPIO6	GPIO_X_MASK(6)
#define GPIO7	GPIO_X_MASK(7)
#define GPIO8	GPIO_X_MASK(8)
#define GPIO9	GPIO_X_MASK(9)
#define GPIO10	GPIO_X_MASK(10)
#define GPIO11	GPIO_X_MASK(11)
#define GPIO12	GPIO_X_MASK(12)
#define GPIO13	GPIO_X_MASK(13)
#define GPIO14	GPIO_X_MASK(14)
#define GPIO15	GPIO_X_MASK(15)
#define GPIO16	GPIO_X_MASK(16)
#define GPIO17	GPIO_X_MASK(17)
#define GPIO18	GPIO_X_MASK(18)
#define GPIO19	GPIO_X_MASK(19)
#define GPIO20	GPIO_X_MASK(20)
#define GPIO21	GPIO_X_MASK(21)
#define GPIO22	GPIO_X_MASK(22)
#define GPIO23	GPIO_X_MASK(23)
#define GPIO24	GPIO_X_MASK(24)
#define GPIO25	GPIO_X_MASK(25)
#define GPIO26	GPIO_X_MASK(26)
#define GPIO27	GPIO_X_MASK(27)
#define GPIO28	GPIO_X_MASK(28)
#define GPIO29	GPIO_X_MASK(29)
#define GPIO30	GPIO_X_MASK(30)
#define GPIO31	GPIO_X_MASK(31)
#define GPIO32	GPIO_X_MASK(32)
#define GPIO33	GPIO_X_MASK(33)
#define GPIO34	GPIO_X_MASK(34)
#define GPIO35	GPIO_X_MASK(35)
#define GPIO36	GPIO_X_MASK(36)
#define GPIO37	GPIO_X_MASK(37)
#define GPIO38	GPIO_X_MASK(38)
#define GPIO39	GPIO_X_MASK(39)
#define GPIO40	GPIO_X_MASK(40)
#define GPIO41	GPIO_X_MASK(41)
#define GPIO42	GPIO_X_MASK(42)
#define GPIO43	GPIO_X_MASK(43)
#define GPIO44	GPIO_X_MASK(44)
#define GPIO45	GPIO_X_MASK(45)
#define GPIO46	GPIO_X_MASK(46)
#define GPIO47	GPIO_X_MASK(47)
#define GPIO48	GPIO_X_MASK(48)
#define GPIO49	GPIO_X_MASK(49)
#define GPIO50	GPIO_X_MASK(50)

/*
 * GPIO registers
 */
#define QCA_GPIO_COUNT	30

/* JTAG GPIO pin mask */
#define QCA_GPIO_JTAG_MASK	0x200001C0	/* GPIO6~8, GPIO29 */

#define QCA_GPIO_OE_REG			QCA_GPIO_BASE_REG + 0x00
#define QCA_GPIO_IN_REG			QCA_GPIO_BASE_REG + 0x04
#define QCA_GPIO_OUT_REG		QCA_GPIO_BASE_REG + 0x08
#define QCA_GPIO_SET_REG		QCA_GPIO_BASE_REG + 0x0C
#define QCA_GPIO_CLEAR_REG		QCA_GPIO_BASE_REG + 0x10
#define QCA_GPIO_INT_EN_REG		QCA_GPIO_BASE_REG + 0x14
#define QCA_GPIO_INT_TYPE_REG		QCA_GPIO_BASE_REG + 0x18
#define QCA_GPIO_INT_POLARITY_REG	QCA_GPIO_BASE_REG + 0x1C
#define QCA_GPIO_INT_PENDING_REG	QCA_GPIO_BASE_REG + 0x20
#define QCA_GPIO_INT_MASK_REG		QCA_GPIO_BASE_REG + 0x24

#define QCA_GPIO_FUNC_1_REG			QCA_GPIO_BASE_REG + 0x28
#define QCA_GPIO_IN_ETH_SWITCH_LED_REG		QCA_GPIO_BASE_REG + 0x2C
#define QCA_GPIO_FUNC_2_REG			QCA_GPIO_BASE_REG + 0x30
#define QCA_GPIO_WLAN_MUX_SET0_REG		QCA_GPIO_BASE_REG + 0x34
#define QCA_GPIO_WLAN_MUX_SET1_REG		QCA_GPIO_BASE_REG + 0x38
#define QCA_GPIO_WLAN_MUX_SET2_REG		QCA_GPIO_BASE_REG + 0x3C
#define QCA_GPIO_WLAN_MUX_SET3_REG		QCA_GPIO_BASE_REG + 0x40

/*
 * GPIO registers BIT fields
 */

/* GPIO_FUNCTION_1/2 register (GPIO function) */
#define QCA_GPIO_FUNC_1_JTAG_DIS_SHIFT		0
#define QCA_GPIO_FUNC_1_JTAG_DIS_MASK		BIT(QCA_GPIO_FUNC_1_JTAG_DIS_SHIFT)
#define QCA_GPIO_FUNC_1_UART_EN_SHIFT		1
#define QCA_GPIO_FUNC_1_UART_EN_MASK		BIT(QCA_GPIO_FUNC_1_UART_EN_SHIFT)
#define QCA_GPIO_FUNC_1_UART_RTS_CTS_EN_SHIFT	2
#define QCA_GPIO_FUNC_1_UART_RTS_CTS_EN_MASK	BIT(QCA_GPIO_FUNC_1_UART_RTS_CTS_EN_SHIFT)
#define QCA_GPIO_FUNC_1_ETH_SW_LED0_EN_SHIFT	3
#define QCA_GPIO_FUNC_1_ETH_SW_LED0_EN_MASK	BIT(QCA_GPIO_FUNC_1_ETH_SW_LED0_EN_SHIFT)
#define QCA_GPIO_FUNC_1_ETH_SW_LED1_EN_SHIFT	4
#define QCA_GPIO_FUNC_1_ETH_SW_LED1_EN_MASK	BIT(QCA_GPIO_FUNC_1_ETH_SW_LED1_EN_SHIFT)
#define QCA_GPIO_FUNC_1_ETH_SW_LED2_EN_SHIFT	5
#define QCA_GPIO_FUNC_1_ETH_SW_LED2_EN_MASK	BIT(QCA_GPIO_FUNC_1_ETH_SW_LED2_EN_SHIFT)
#define QCA_GPIO_FUNC_1_ETH_SW_LED3_EN_SHIFT	6
#define QCA_GPIO_FUNC_1_ETH_SW_LED3_EN_MASK	BIT(QCA_GPIO_FUNC_1_ETH_SW_LED3_EN_SHIFT)
#define QCA_GPIO_FUNC_1_ETH_SW_LED4_EN_SHIFT	7
#define QCA_GPIO_FUNC_1_ETH_SW_LED4_EN_MASK	BIT(QCA_GPIO_FUNC_1_ETH_SW_LED4_EN_SHIFT)
#define QCA_GPIO_FUNC_1_SPI_CS_EN1_SHIFT	13
#define QCA_GPIO_FUNC_1_SPI_CS_EN1_MASK		BIT(QCA_GPIO_FUNC_1_SPI_CS_EN1_SHIFT)
#define QCA_GPIO_FUNC_1_SPI_CS_EN2_SHIFT	14
#define QCA_GPIO_FUNC_1_SPI_CS_EN2_MASK		BIT(QCA_GPIO_FUNC_1_SPI_CS_EN2_SHIFT)
#define QCA_GPIO_FUNC_1_SPI_EN_SHIFT		18
#define QCA_GPIO_FUNC_1_SPI_EN_MASK		BIT(QCA_GPIO_FUNC_1_SPI_EN_SHIFT)
#define QCA_GPIO_FUNC_1_ETH_SW_LED_ACT_SHIFT	23
#define QCA_GPIO_FUNC_1_ETH_SW_LED_ACT_MASK	BIT(QCA_GPIO_FUNC_1_ETH_SW_LED_ACT_SHIFT)
#define QCA_GPIO_FUNC_1_ETH_SW_LED_COLL_SHIFT	24
#define QCA_GPIO_FUNC_1_ETH_SW_LED_COLL_MASK	BIT(QCA_GPIO_FUNC_1_ETH_SW_LED_COLL_SHIFT)
#define QCA_GPIO_FUNC_1_ETH_SW_LED_DUPL_SHIFT	25
#define QCA_GPIO_FUNC_1_ETH_SW_LED_DUPL_MASK	BIT(QCA_GPIO_FUNC_1_ETH_SW_LED_DUPL_SHIFT)
#define QCA_GPIO_FUNC_1_I2S_EN_SHIFT		26
#define QCA_GPIO_FUNC_1_I2S_EN_MASK		BIT(QCA_GPIO_FUNC_1_I2S_EN_SHIFT)
#define QCA_GPIO_FUNC_1_I2S_MCLK_EN_SHIFT	27
#define QCA_GPIO_FUNC_1_I2S_MCLK_EN_MASK	BIT(QCA_GPIO_FUNC_1_I2S_MCLK_EN_SHIFT)
#define QCA_GPIO_FUNC_1_I2S_22_18_EN_SHIFT	29
#define QCA_GPIO_FUNC_1_I2S_22_18_EN_MASK	BIT(QCA_GPIO_FUNC_1_I2S_22_18_EN_SHIFT)
#define QCA_GPIO_FUNC_1_SPDIF_EN_SHIFT		30
#define QCA_GPIO_FUNC_1_SPDIF_EN_MASK		BIT(QCA_GPIO_FUNC_1_SPDIF_EN_SHIFT)
#define QCA_GPIO_FUNC_1_SPDIF_TCK_EN_SHIFT	31
#define QCA_GPIO_FUNC_1_SPDIF_TCK_EN_MASK	BIT(QCA_GPIO_FUNC_1_SPDIF_TCK_EN_SHIFT)

#define QCA_GPIO_FUNC_2_MIC_DIS_SHIFT		0
#define QCA_GPIO_FUNC_2_MIC_DIS_MASK		BIT(QCA_GPIO_FUNC_2_MIC_DIS_SHIFT)
#define QCA_GPIO_FUNC_2_I2S_ON_LED_SHIFT	1
#define QCA_GPIO_FUNC_2_I2S_ON_LED_MASK		BIT(QCA_GPIO_FUNC_2_I2S_ON_LED_SHIFT)
#define QCA_GPIO_FUNC_2_SPDIF_ON23_SHIFT	2
#define QCA_GPIO_FUNC_2_SPDIF_ON23_MASK		BIT(QCA_GPIO_FUNC_2_SPDIF_ON23_SHIFT)
#define QCA_GPIO_FUNC_2_I2SCK_ON1_SHIFT		3
#define QCA_GPIO_FUNC_2_I2SCK_ON1_MASK		BIT(QCA_GPIO_FUNC_2_I2SCK_ON1_SHIFT)
#define QCA_GPIO_FUNC_2_I2SWS_ON0_SHIFT		4
#define QCA_GPIO_FUNC_2_I2SWS_ON0_MASK		BIT(QCA_GPIO_FUNC_2_I2SWS_ON0_SHIFT)
#define QCA_GPIO_FUNC_2_I2SSD_ON12_SHIFT	5
#define QCA_GPIO_FUNC_2_I2SSD_ON12_MASK		BIT(QCA_GPIO_FUNC_2_I2SSD_ON12_SHIFT)
#define QCA_GPIO_FUNC_2_WPS_DIS_SHIFT		8
#define QCA_GPIO_FUNC_2_WPS_DIS_MASK		BIT(QCA_GPIO_FUNC_2_WPS_DIS_SHIFT)
#define QCA_GPIO_FUNC_2_JUMPSTART_DIS_SHIFT	9
#define QCA_GPIO_FUNC_2_JUMPSTART_DIS_MASK	BIT(QCA_GPIO_FUNC_2_JUMPSTART_DIS_SHIFT)
#define QCA_GPIO_FUNC_2_WLAN_LED_ON0_SHIFT	10
#define QCA_GPIO_FUNC_2_WLAN_LED_ON0_MASK	BIT(QCA_GPIO_FUNC_2_WLAN_LED_ON0_SHIFT)
#define QCA_GPIO_FUNC_2_USB_LED_ON1_SHIFT	11
#define QCA_GPIO_FUNC_2_USB_LED_ON1_MASK	BIT(QCA_GPIO_FUNC_2_USB_LED_ON1_SHIFT)
#define QCA_GPIO_FUNC_2_LNA_ON28_SHIFT		12
#define QCA_GPIO_FUNC_2_LNA_ON28_MASK		BIT(QCA_GPIO_FUNC_2_LNA_ON28_SHIFT)
#define QCA_GPIO_FUNC_2_SLIC_EN_SHIFT		13
#define QCA_GPIO_FUNC_2_SLIC_EN_MASK		BIT(QCA_GPIO_FUNC_2_SLIC_EN_SHIFT)
#define QCA_GPIO_FUNC_2_SLIC_ON18_22_SHIFT	14
#define QCA_GPIO_FUNC_2_SLIC_ON18_22_MASK	BIT(QCA_GPIO_FUNC_2_SLIC_ON18_22_SHIFT)
#define QCA_GPIO_FUNC_2_SLIC_DIO_MUX_EN_SHIFT	15
#define QCA_GPIO_FUNC_2_SLIC_DIO_MUX_EN_MASK	BIT(QCA_GPIO_FUNC_2_SLIC_DIO_MUX_EN_SHIFT)
#define QCA_GPIO_FUNC_2_MDIO_SLAVE_ADDR_SHIFT	16
#define QCA_GPIO_FUNC_2_MDIO_SLAVE_ADDR_MASK	BITS(QCA_GPIO_FUNC_2_MDIO_SLAVE_ADDR_SHIFT, 3)

/*
 * GPIO MUX
 */
#define QCA_GPIO_OUT_FUNCX_GPIOX_EN_SHIFT(_gpio)	((_gpio % 4) * 8)
#define QCA_GPIO_OUT_FUNCX_GPIOX_EN_MASK(_gpio)		BIT(((_gpio % 4) * 8), 8)

#define QCA_GPIO_OUT_FUNCX_GPIO0_EN_SHIFT	0
#define QCA_GPIO_OUT_FUNCX_GPIO4_EN_SHIFT	0
#define QCA_GPIO_OUT_FUNCX_GPIO8_EN_SHIFT	0
#define QCA_GPIO_OUT_FUNCX_GPIO12_EN_SHIFT	0
#define QCA_GPIO_OUT_FUNCX_GPIO16_EN_SHIFT	0
#define QCA_GPIO_OUT_FUNCX_GPIO20_EN_SHIFT	0
#define QCA_GPIO_OUT_FUNCX_GPIO0_EN_MASK	BITS(QCA_GPIO_OUT_FUNCX_GPIO0_EN_SHIFT, 8)
#define QCA_GPIO_OUT_FUNCX_GPIO4_EN_MASK	BITS(QCA_GPIO_OUT_FUNCX_GPIO4_EN_SHIFT, 8)
#define QCA_GPIO_OUT_FUNCX_GPIO8_EN_MASK	BITS(QCA_GPIO_OUT_FUNCX_GPIO8_EN_SHIFT, 8)
#define QCA_GPIO_OUT_FUNCX_GPIO12_EN_MASK	BITS(QCA_GPIO_OUT_FUNCX_GPIO12_EN_SHIFT, 8)
#define QCA_GPIO_OUT_FUNCX_GPIO16_EN_MASK	BITS(QCA_GPIO_OUT_FUNCX_GPIO16_EN_SHIFT, 8)
#define QCA_GPIO_OUT_FUNCX_GPIO20_EN_MASK	BITS(QCA_GPIO_OUT_FUNCX_GPIO20_EN_SHIFT, 8)

#define QCA_GPIO_OUT_FUNCX_GPIO1_EN_SHIFT	8
#define QCA_GPIO_OUT_FUNCX_GPIO5_EN_SHIFT	8
#define QCA_GPIO_OUT_FUNCX_GPIO9_EN_SHIFT	8
#define QCA_GPIO_OUT_FUNCX_GPIO13_EN_SHIFT	8
#define QCA_GPIO_OUT_FUNCX_GPIO17_EN_SHIFT	8
#define QCA_GPIO_OUT_FUNCX_GPIO21_EN_SHIFT	8
#define QCA_GPIO_OUT_FUNCX_GPIO1_EN_MASK	BITS(QCA_GPIO_OUT_FUNCX_GPIO1_EN_SHIFT, 8)
#define QCA_GPIO_OUT_FUNCX_GPIO5_EN_MASK	BITS(QCA_GPIO_OUT_FUNCX_GPIO5_EN_SHIFT, 8)
#define QCA_GPIO_OUT_FUNCX_GPIO9_EN_MASK	BITS(QCA_GPIO_OUT_FUNCX_GPIO9_EN_SHIFT, 8)
#define QCA_GPIO_OUT_FUNCX_GPIO13_EN_MASK	BITS(QCA_GPIO_OUT_FUNCX_GPIO13_EN_SHIFT, 8)
#define QCA_GPIO_OUT_FUNCX_GPIO17_EN_MASK	BITS(QCA_GPIO_OUT_FUNCX_GPIO17_EN_SHIFT, 8)
#define QCA_GPIO_OUT_FUNCX_GPIO21_EN_MASK	BITS(QCA_GPIO_OUT_FUNCX_GPIO21_EN_SHIFT, 8)

#define QCA_GPIO_OUT_FUNCX_GPIO2_EN_SHIFT	16
#define QCA_GPIO_OUT_FUNCX_GPIO6_EN_SHIFT	16
#define QCA_GPIO_OUT_FUNCX_GPIO10_EN_SHIFT	16
#define QCA_GPIO_OUT_FUNCX_GPIO14_EN_SHIFT	16
#define QCA_GPIO_OUT_FUNCX_GPIO18_EN_SHIFT	16
#define QCA_GPIO_OUT_FUNCX_GPIO22_EN_SHIFT	16
#define QCA_GPIO_OUT_FUNCX_GPIO2_EN_MASK	BITS(QCA_GPIO_OUT_FUNCX_GPIO2_EN_SHIFT, 8)
#define QCA_GPIO_OUT_FUNCX_GPIO6_EN_MASK	BITS(QCA_GPIO_OUT_FUNCX_GPIO6_EN_SHIFT, 8)
#define QCA_GPIO_OUT_FUNCX_GPIO10_EN_MASK	BITS(QCA_GPIO_OUT_FUNCX_GPIO10_EN_SHIFT, 8)
#define QCA_GPIO_OUT_FUNCX_GPIO14_EN_MASK	BITS(QCA_GPIO_OUT_FUNCX_GPIO14_EN_SHIFT, 8)
#define QCA_GPIO_OUT_FUNCX_GPIO18_EN_MASK	BITS(QCA_GPIO_OUT_FUNCX_GPIO18_EN_SHIFT, 8)
#define QCA_GPIO_OUT_FUNCX_GPIO22_EN_MASK	BITS(QCA_GPIO_OUT_FUNCX_GPIO22_EN_SHIFT, 8)

#define QCA_GPIO_OUT_FUNCX_GPIO3_EN_SHIFT	24
#define QCA_GPIO_OUT_FUNCX_GPIO7_EN_SHIFT	24
#define QCA_GPIO_OUT_FUNCX_GPIO11_EN_SHIFT	24
#define QCA_GPIO_OUT_FUNCX_GPIO15_EN_SHIFT	24
#define QCA_GPIO_OUT_FUNCX_GPIO19_EN_SHIFT	24
#define QCA_GPIO_OUT_FUNCX_GPIO23_EN_SHIFT	24
#define QCA_GPIO_OUT_FUNCX_GPIO3_EN_MASK	BITS(QCA_GPIO_OUT_FUNCX_GPIO3_EN_SHIFT, 8)
#define QCA_GPIO_OUT_FUNCX_GPIO7_EN_MASK	BITS(QCA_GPIO_OUT_FUNCX_GPIO7_EN_SHIFT, 8)
#define QCA_GPIO_OUT_FUNCX_GPIO11_EN_MASK	BITS(QCA_GPIO_OUT_FUNCX_GPIO11_EN_SHIFT, 8)
#define QCA_GPIO_OUT_FUNCX_GPIO15_EN_MASK	BITS(QCA_GPIO_OUT_FUNCX_GPIO15_EN_SHIFT, 8)
#define QCA_GPIO_OUT_FUNCX_GPIO19_EN_MASK	BITS(QCA_GPIO_OUT_FUNCX_GPIO19_EN_SHIFT, 8)
#define QCA_GPIO_OUT_FUNCX_GPIO23_EN_MASK	BITS(QCA_GPIO_OUT_FUNCX_GPIO23_EN_SHIFT, 8)

/* GPIO output select values (for MUX) */
#define QCA_GPIO_OUT_MUX_GPIO_VAL		0
#define QCA_GPIO_OUT_MUX_MII_EXT_MDI_VAL	1
#define QCA_GPIO_OUT_MUX_SYS_RST_L_VAL		1
#define QCA_GPIO_OUT_MUX_NAND_CS0_VAL		1
#define QCA_GPIO_OUT_MUX_BOOT_RXT_MDI_VAL	2
#define QCA_GPIO_OUT_MUX_SPI_CS0_VAL		9

/* 5-port ethernet switch activity LEDs */
#define QCA_GPIO_OUT_MUX_ETH_SW_LED_ACTN1_VAL	26
#define QCA_GPIO_OUT_MUX_ETH_SW_LED_ACTN2_VAL	27
#define QCA_GPIO_OUT_MUX_ETH_SW_LED_ACTN3_VAL	28
#define QCA_GPIO_OUT_MUX_ETH_SW_LED_ACTN4_VAL	29
#define QCA_GPIO_OUT_MUX_ETH_SW_LED_ACTN5_VAL	30

/* 5-port ethernet switch collision detect LEDs */
#define QCA_GPIO_OUT_MUX_ETH_SW_LED_COLN1_VAL	31
#define QCA_GPIO_OUT_MUX_ETH_SW_LED_COLN2_VAL	32
#define QCA_GPIO_OUT_MUX_ETH_SW_LED_COLN3_VAL	33
#define QCA_GPIO_OUT_MUX_ETH_SW_LED_COLN4_VAL	34
#define QCA_GPIO_OUT_MUX_ETH_SW_LED_COLN5_VAL	35

/* 5-port ethernet switch full/half duplex LEDs */
#define QCA_GPIO_OUT_MUX_ETH_SW_LED_DUPN1_VAL	36
#define QCA_GPIO_OUT_MUX_ETH_SW_LED_DUPN2_VAL	37
#define QCA_GPIO_OUT_MUX_ETH_SW_LED_DUPN3_VAL	38
#define QCA_GPIO_OUT_MUX_ETH_SW_LED_DUPN4_VAL	39
#define QCA_GPIO_OUT_MUX_ETH_SW_LED_DUPN5_VAL	40

/* 5-port ethernet switch link indicator LEDs */
#define QCA_GPIO_OUT_MUX_ETH_SW_LED_LINK1_VAL	41
#define QCA_GPIO_OUT_MUX_ETH_SW_LED_LINK2_VAL	42
#define QCA_GPIO_OUT_MUX_ETH_SW_LED_LINK3_VAL	43
#define QCA_GPIO_OUT_MUX_ETH_SW_LED_LINK4_VAL	44
#define QCA_GPIO_OUT_MUX_ETH_SW_LED_LINK5_VAL	45
#define QCA_GPIO_OUT_MUX_SLIC_DATA_OUT_VAL			3
#define QCA_GPIO_OUT_MUX_SLIC_PCM_FS_VAL			4
#define QCA_GPIO_OUT_MUX_SLIC_PCM_CLK_VAL			5
#define QCA_GPIO_OUT_MUX_SPI_CLK_VAL				8
#define QCA_GPIO_OUT_MUX_SPI_CS1_VAL				10
#define QCA_GPIO_OUT_MUX_SPI_CS2_VAL				11
#define QCA_GPIO_OUT_MUX_SPI_MOSI_VAL				12
#define QCA_GPIO_OUT_MUX_I2S_CLK_VAL				13
#define QCA_GPIO_OUT_MUX_I2S_WS_VAL				14
#define QCA_GPIO_OUT_MUX_I2S_SD_VAL				15
#define QCA_GPIO_OUT_MUX_I2S_MCLK_VAL				16
#define QCA_GPIO_OUT_MUX_SPDIF_OUT_VAL				17
#define QCA_GPIO_OUT_MUX_HSUART_TXD_VAL				18
#define QCA_GPIO_OUT_MUX_HSUART_RTS_VAL				19
#define QCA_GPIO_OUT_MUX_HSUART_RXD_VAL				20	/* TODO: RXD is INPUT, mistake in QCA9558 datasheet? */
#define QCA_GPIO_OUT_MUX_HSUART_CTS_VAL				21	/* TODO: CTS is INPUT, mistake in QCA9558 datasheet? */
#define QCA_GPIO_OUT_MUX_LSUART_TXD_VAL				22
#define QCA_GPIO_OUT_MUX_SRIF_OUT_VAL				23

/* GPIO_IN_ENABLE0 register (GPIO in signals 0) */
#define QCA_GPIO_IN_EN0_SPI_MISO_SHIFT		0
#define QCA_GPIO_IN_EN0_SPI_MISO_MASK		BITS(QCA_GPIO_IN_EN0_SPI_MISO_SHIFT, 8)
#define QCA_GPIO_IN_EN0_LSUART_RXD_SHIFT	8
#define QCA_GPIO_IN_EN0_LSUART_RXD_MASK		BITS(QCA_GPIO_IN_EN0_LSUART_RXD_SHIFT ,8)

/* GPIO_IN_ENABLE1 register (GPIO in signals 1) */
#define QCA_GPIO_IN_EN1_I2S_WS_SHIFT		0
#define QCA_GPIO_IN_EN1_I2S_WS_MASK		BITS(QCA_GPIO_IN_EN1_I2S_WS_SHIFT ,8)
#define QCA_GPIO_IN_EN1_I2S_MIC_SD_SHIFT	8
#define QCA_GPIO_IN_EN1_I2S_MIC_SD_MASK		BITS(QCA_GPIO_IN_EN1_I2S_MIC_SD_SHIFT ,8)
#define QCA_GPIO_IN_EN1_I2S_CLK_SHIFT		16
#define QCA_GPIO_IN_EN1_I2S_CLK_MASK		BITS(QCA_GPIO_IN_EN1_I2S_CLK_SHIFT ,8)
#define QCA_GPIO_IN_EN1_I2S_MCLK_SHIFT		24
#define QCA_GPIO_IN_EN1_I2S_MCLK_MASK		BITS(QCA_GPIO_IN_EN1_I2S_MCLK_SHIFT ,8)

/* GPIO_IN_ENABLE9 register (GPIO in signals 9) */
#define QCA_GPIO_IN_EN9_HSUART_RXD_SHIFT	16
#define QCA_GPIO_IN_EN9_HSUART_RXD_MASK		BITS(QCA_GPIO_IN_EN9_HSUART_RXD_SHIFT ,8)
#define QCA_GPIO_IN_EN9_HSUART_CTS_SHIFT	24
#define QCA_GPIO_IN_EN9_HSUART_CTS_MASK		BITS(QCA_GPIO_IN_EN9_HSUART_CTS_SHIFT ,8)

/* GPIO_FUNCTION register (GPIO function) */
#define QCA_GPIO_FUNC_GPIO_SRIF_EN_SHIFT	0
#define QCA_GPIO_FUNC_GPIO_SRIF_EN_MASK		BIT(QCA_GPIO_FUNC_GPIO_SRIF_EN_SHIFT)
#define QCA_GPIO_FUNC_JTAG_DIS_SHIFT		1
#define QCA_GPIO_FUNC_JTAG_DIS_MASK		BIT(QCA_GPIO_FUNC_JTAG_DIS_SHIFT)
#define QCA_GPIO_FUNC_CLK_OBS0_EN_SHIFT		2
#define QCA_GPIO_FUNC_CLK_OBS0_EN_MASK		BIT(QCA_GPIO_FUNC_CLK_OBS0_EN_SHIFT)
#define QCA_GPIO_FUNC_CLK_OBS1_EN_SHIFT		3
#define QCA_GPIO_FUNC_CLK_OBS1_EN_MASK		BIT(QCA_GPIO_FUNC_CLK_OBS1_EN_SHIFT)
#define QCA_GPIO_FUNC_CLK_OBS2_EN_SHIFT		4
#define QCA_GPIO_FUNC_CLK_OBS2_EN_MASK		BIT(QCA_GPIO_FUNC_CLK_OBS2_EN_SHIFT)
#define QCA_GPIO_FUNC_CLK_OBS3_EN_SHIFT		5
#define QCA_GPIO_FUNC_CLK_OBS3_EN_MASK		BIT(QCA_GPIO_FUNC_CLK_OBS3_EN_SHIFT)
#define QCA_GPIO_FUNC_CLK_OBS4_EN_SHIFT		6
#define QCA_GPIO_FUNC_CLK_OBS4_EN_MASK		BIT(QCA_GPIO_FUNC_CLK_OBS4_EN_SHIFT)
#define QCA_GPIO_FUNC_CLK_OBS5_EN_SHIFT		7
#define QCA_GPIO_FUNC_CLK_OBS5_EN_MASK		BIT(QCA_GPIO_FUNC_CLK_OBS5_EN_SHIFT)
#define QCA_GPIO_FUNC_CLK_OBS6_EN_SHIFT		8
#define QCA_GPIO_FUNC_CLK_OBS6_EN_MASK		BIT(QCA_GPIO_FUNC_CLK_OBS6_EN_SHIFT)
#define QCA_GPIO_FUNC_CLK_OBS7_EN_SHIFT		9
#define QCA_GPIO_FUNC_CLK_OBS7_EN_MASK		BIT(QCA_GPIO_FUNC_CLK_OBS7_EN_SHIFT)

void ar933x_all_led_on(void);

#endif /* _SOC_COMMON_H_ */
