/*
 * SOC common registers and helper function/macro definitions
 *
 * Copyright (C) 2016 Piotr Dymacz <piotr@dymacz.pl>
 *
 * SPDX-License-Identifier: GPL-2.0
 */

#ifndef _AR933X_RESET_H_
#define _AR933X_RESET_H_

/*
 * Reset control registers
 */
#define QCA_RST_GENERAL_TIMER1_REG		QCA_RST_BASE_REG + 0x00
#define QCA_RST_GENERAL_TIMER1_RELOAD_REG	QCA_RST_BASE_REG + 0x04
#define QCA_RST_WATCHDOG_TIMER_CTRL_REG		QCA_RST_BASE_REG + 0x08
#define QCA_RST_WATCHDOG_TIMER_REG		QCA_RST_BASE_REG + 0x0C
#define QCA_RST_MISC_INTERRUPT_STATUS_REG	QCA_RST_BASE_REG + 0x10
#define QCA_RST_MISC_INTERRUPT_MASK_REG		QCA_RST_BASE_REG + 0x14
#define QCA_RST_GLOBALINTERRUPT_STATUS_REG	QCA_RST_BASE_REG + 0x18
#define QCA_RST_RESET_REG			QCA_RST_BASE_REG + 0x1C
#define QCA_RST_REVISION_ID_REG			QCA_RST_BASE_REG + 0x90
#define QCA_RST_GENERAL_TIMER2_REG		QCA_RST_BASE_REG + 0x94
#define QCA_RST_GENERAL_TIMER2_RELOAD_REG	QCA_RST_BASE_REG + 0x98
#define QCA_RST_GENERAL_TIMER3_REG		QCA_RST_BASE_REG + 0x9C
#define QCA_RST_GENERAL_TIMER3_RELOAD_REG	QCA_RST_BASE_REG + 0xA0
#define QCA_RST_GENERAL_TIMER4_REG		QCA_RST_BASE_REG + 0xA4
#define QCA_RST_GENERAL_TIMER4_RELOAD_REG	QCA_RST_BASE_REG + 0xA8
#define QCA_RST_BOOTSTRAP_REG		QCA_RST_BASE_REG + 0xAC
#define QCA_RST_MISC2_REG		QCA_RST_BASE_REG + 0xBC
#define QCA_RST_RESET2_REG		QCA_RST_BASE_REG + 0xC4

/*
 * Reset control registers BIT fields
 */

/* RST_WATCHDOG_TIMER_CTRL (Watchdog timer control) */
#define QCA_RST_WATCHDOG_TIMER_CTRL_ACTION_SHIFT	0
#define QCA_RST_WATCHDOG_TIMER_CTRL_ACTION_MASK		BITS(QCA_RST_WATCHDOG_TIMER_CTRL_ACTION_SHIFT, 2)
#define QCA_RST_WATCHDOG_TIMER_CTRL_LAST_SHIFT		31
#define QCA_RST_WATCHDOG_TIMER_CTRL_LAST_MASK		BIT(QCA_RST_WATCHDOG_TIMER_CTRL_LAST_SHIFT)

/* RST_BOOTSTRAP (Reset bootstrap) */
#define QCA_RST_BOOTSTRAP_REF_CLK_SHIFT		0
#define QCA_RST_BOOTSTRAP_REF_CLK_MASK			BIT(QCA_RST_BOOTSTRAP_REF_CLK_SHIFT)
#define QCA_RST_BOOTSTRAP_REF_CLK_25M_VAL		0x0
#define QCA_RST_BOOTSTRAP_REF_CLK_40M_VAL		0x1

#define QCA_RST_BOOTSTRAP_USB_MODE_DEV_SHIFT	3
#define QCA_RST_BOOTSTRAP_USB_MODE_DEV_MASK	BIT(QCA_RST_BOOTSTRAP_USB_MODE_DEV_SHIFT)
#define QCA_RST_BOOTSTRAP_EEPBUSY_SHIFT		4
#define QCA_RST_BOOTSTRAP_EEPBUSY_MASK		BIT(QCA_RST_BOOTSTRAP_EEPBUSY_SHIFT)
#define QCA_RST_BOOTSTRAP_MEM_TYPE_SHIFT	12
#define QCA_RST_BOOTSTRAP_MEM_TYPE_MASK		BITS(QCA_RST_BOOTSTRAP_MEM_TYPE_SHIFT, 2)
#define QCA_RST_BOOTSTRAP_JTAG_APB_SEL_SHIFT	16
#define QCA_RST_BOOTSTRAP_JTAG_APB_SEL_MASK	BIT(QCA_RST_BOOTSTRAP_JTAG_APB_SEL_SHIFT)
#define QCA_RST_BOOTSTRAP_MDIO_SLAVE_EN_SHIFT	17
#define QCA_RST_BOOTSTRAP_MDIO_SLAVE_EN_MASK	BIT(QCA_RST_BOOTSTRAP_MDIO_SLAVE_EN_SHIFT)
#define QCA_RST_BOOTSTRAP_MDIO_GPIO_EN_SHIFT	18
#define QCA_RST_BOOTSTRAP_MDIO_GPIO_EN_MASK	BIT(QCA_RST_BOOTSTRAP_MDIO_GPIO_EN_SHIFT)

#define QCA_RST_BOOTSTRAP_MEM_TYPE_SDR_VAL	0
#define QCA_RST_BOOTSTRAP_MEM_TYPE_DDR1_VAL	1
#define QCA_RST_BOOTSTRAP_MEM_TYPE_DDR2_VAL	2

/* RST_RESET */
#define QCA_RST_RESET_I2S_RST_SHIFT			0
#define QCA_RST_RESET_I2S_RST_MASK			BIT(QCA_RST_RESET_I2S_RST_SHIFT)
#define QCA_RST_RESET_LUT_RST_SHIFT			2
#define QCA_RST_RESET_LUT_RST_MASK			BIT(QCA_RST_RESET_LUT_RST_SHIFT)

#define QCA_RST_RESET_MBOX_RST_SHIFT				1
#define QCA_RST_RESET_MBOX_RST_MASK				BIT(QCA_RST_RESET_MBOX_RST_SHIFT)
#define QCA_RST_RESET_USB_PHY_SUSPEND_ORIDE_SHIFT		3
#define QCA_RST_RESET_USB_PHY_SUSPEND_ORIDE_MASK		BIT(QCA_RST_RESET_USB_PHY_SUSPEND_ORIDE_SHIFT)
#define QCA_RST_RESET_USB_PHY_RST_SHIFT				4
#define QCA_RST_RESET_USB_PHY_RST_MASK				BIT(QCA_RST_RESET_USB_PHY_RST_SHIFT)
#define QCA_RST_RESET_USB_HOST_RST_SHIFT			5
#define QCA_RST_RESET_USB_HOST_RST_MASK				BIT(QCA_RST_RESET_USB_HOST_RST_SHIFT)

#define QCA_RST_RESET_SLIC_RST_SHIFT			6
#define QCA_RST_RESET_SLIC_RST_MASK			BIT(QCA_RST_RESET_SLIC_RST_SHIFT)

#define QCA_RST_RESET_PCIE_PHY_RST_SHIFT			7
#define QCA_RST_RESET_PCIE_PHY_RST_MASK				BIT(QCA_RST_RESET_PCIE_PHY_RST_SHIFT)

#define QCA_RST_RESET_ETH_SWITCH_RST_SHIFT		8
#define QCA_RST_RESET_ETH_SWITCH_RST_MASK		BIT(QCA_RST_RESET_ETH_SWITCH_RST_SHIFT)

#define QCA_RST_RESET_GE0_MAC_RST_SHIFT				9
#define QCA_RST_RESET_GE0_MAC_RST_MASK				BIT(QCA_RST_RESET_GE0_MAC_RST_SHIFT)
#define QCA_RST_RESET_HOST_DMA_INT_SHIFT			10
#define QCA_RST_RESET_HOST_DMA_INT_MASK				BIT(QCA_RST_RESET_HOST_DMA_INT_SHIFT)

#define QCA_RST_RESET_WLAN_RST_SHIFT			11
#define QCA_RST_RESET_WLAN_RST_MASK			BIT(QCA_RST_RESET_WLAN_RST_SHIFT)

#define QCA_RST_RESET_ETH_SWITCH_ARST_SHIFT		14
#define QCA_RST_RESET_ETH_SWITCH_ARST_MASK		BIT(QCA_RST_RESET_ETH_SWITCH_ARST_SHIFT)

#define QCA_RST_RESET_GE1_MAC_RST_SHIFT				13
#define QCA_RST_RESET_GE1_MAC_RST_MASK				BIT(QCA_RST_RESET_GE1_MAC_RST_SHIFT)
#define QCA_RST_RESET_USB_PHY_PLLPWD_EXT_SHIFT			15
#define QCA_RST_RESET_USB_PHY_PLLPWD_EXT_MASK			BIT(QCA_RST_RESET_USB_PHY_PLLPWD_EXT_SHIFT)
#define QCA_RST_RESET_DDR_RST_SHIFT				16
#define QCA_RST_RESET_DDR_RST_MASK				BIT(QCA_RST_RESET_DDR_RST_SHIFT)
#define QCA_RST_RESET_HSUART_RST_SHIFT				17
#define QCA_RST_RESET_HSUART_RST_MASK				BIT(QCA_RST_RESET_HSUART_RST_SHIFT)
#define QCA_RST_RESET_PCIEEP_RST_SHIFT				18
#define QCA_RST_RESET_PCIEEP_RST_MASK				BIT(QCA_RST_RESET_PCIEEP_RST_SHIFT)
#define QCA_RST_RESET_HOST_DMA_RST_INT_SHIFT			19
#define QCA_RST_RESET_HOST_DMA_RST_INT_MASK			BIT(QCA_RST_RESET_HOST_DMA_RST_INT_SHIFT)
#define QCA_RST_RESET_CPU_COLD_RST_SHIFT			20
#define QCA_RST_RESET_CPU_COLD_RST_MASK				BIT(QCA_RST_RESET_CPU_COLD_RST_SHIFT)
#define QCA_RST_RESET_CPU_NMI_SHIFT				21
#define QCA_RST_RESET_CPU_NMI_MASK				BIT(QCA_RST_RESET_CPU_NMI_SHIFT)
#define QCA_RST_RESET_GE0_MDIO_RST_SHIFT			22
#define QCA_RST_RESET_GE0_MDIO_RST_MASK				BIT(QCA_RST_RESET_GE0_MDIO_RST_SHIFT)
#define QCA_RST_RESET_GE1_MDIO_RST_SHIFT			23
#define QCA_RST_RESET_GE1_MDIO_RST_MASK				BIT(QCA_RST_RESET_GE1_MDIO_RST_SHIFT)
#define QCA_RST_RESET_FULL_CHIP_RST_SHIFT			24
#define QCA_RST_RESET_FULL_CHIP_RST_MASK			BIT(QCA_RST_RESET_FULL_CHIP_RST_SHIFT)
#define QCA_RST_RESET_CHECKSUM_ACC_RST_SHIFT			25
#define QCA_RST_RESET_CHECKSUM_ACC_RST_MASK			BIT(QCA_RST_RESET_CHECKSUM_ACC_RST_SHIFT)
#define QCA_RST_RESET_PCIEEP_RST_INT_SHIFT			26
#define QCA_RST_RESET_PCIEEP_RST_INT_MASK			BIT(QCA_RST_RESET_PCIEEP_RST_INT_SHIFT)
#define QCA_RST_RESET_RTC_RST_SHIFT				27
#define QCA_RST_RESET_RTC_RST_MASK				BIT(QCA_RST_RESET_RTC_RST_SHIFT)
#define QCA_RST_RESET_EXT_RST_SHIFT				28
#define QCA_RST_RESET_EXT_RST_MASK				BIT(QCA_RST_RESET_EXT_RST_SHIFT)

#define QCA_RST_RESET_HOST_DMA_RST_STATUS_SHIFT			31
#define QCA_RST_RESET_HOST_DMA_RST_STATUS_MASK			BIT(QCA_RST_RESET_HOST_DMA_RST_STATUS_SHIFT)

/* RST_REVISION_ID (Chip revision ID) */
#define QCA_RST_REVISION_ID_MAJOR_SHIFT		4
#define QCA_RST_REVISION_ID_MAJOR_MASK		BITS(QCA_RST_REVISION_ID_MAJOR_SHIFT, 12)

#define QCA_RST_REVISION_ID_REV_SHIFT	0
#define QCA_RST_REVISION_ID_REV_MASK	BITS(QCA_RST_REVISION_ID_REV_SHIFT, 2)

#define QCA_RST_REVISION_ID_MAJOR_AR9330_VAL		0x0110
#define QCA_RST_REVISION_ID_MAJOR_AR9331_VAL		0x1110
#define QCA_RST_REVISION_ID_MAJOR_AR9341_VAL		0x0120
#define QCA_RST_REVISION_ID_MAJOR_AR9342_VAL		0x1120
#define QCA_RST_REVISION_ID_MAJOR_AR9344_VAL		0x2120
#define QCA_RST_REVISION_ID_MAJOR_QCA953X_VAL		0x0140
#define QCA_RST_REVISION_ID_MAJOR_QCA953X_V2_VAL	0x0160
#define QCA_RST_REVISION_ID_MAJOR_QCA9558_VAL		0x1130

/* RST_MISC2 register (Miscellaneous CPU control bits) */
#define QCA_RST_MISC2_PERSTN_RCPHY_SHIFT	13
#define QCA_RST_MISC2_PERSTN_RCPHY_MASK		BIT(QCA_RST_MISC2_PERSTN_RCPHY_SHIFT)
#define QCA_RST_MISC2_PERSTN_RCPHY2_SHIFT	14
#define QCA_RST_MISC2_PERSTN_RCPHY2_MASK	BIT(QCA_RST_MISC2_PERSTN_RCPHY2_SHIFT)

void ar933x_full_reset(void);

#endif /* _SOC_COMMON_H_ */
